---
cluster.name: "docker-cluster"

network.host: 0.0.0.0
network.bind_host: 0.0.0.0
network.publish_host: 0.0.0.0

http.host: 0.0.0.0
http.port: 9200
http.cors.enabled: true
http.cors.allow-origin: "*"

transport.host: 0.0.0.0
transport.tcp.port: 9300

node.name: "docker-cluster"
node.master: true
node.data: true

discovery.type: single-node

## X-Pack
#xpack.license.self_generated.type: trial
#xpack.security.enabled: true
#xpack.monitoring.collection.enabled: true
